// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkcgL2wKRHWAQeDsCEr-sWuvervvpbTv0',
    appId: '1:128383511539:web:4c04808b2b608220bbc086',
    messagingSenderId: '128383511539',
    projectId: 'leylaninpaltarlariapp',
    authDomain: 'leylaninpaltarlariapp.firebaseapp.com',
    storageBucket: 'leylaninpaltarlariapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATLIXyMnQGXSyi4oNpyn6SGnCuSTR3Bq0',
    appId: '1:128383511539:android:5e0948ecb4796465bbc086',
    messagingSenderId: '128383511539',
    projectId: 'leylaninpaltarlariapp',
    storageBucket: 'leylaninpaltarlariapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCCGlaR71oG1rbZ5Y-a10J_TUt7NC_glk',
    appId: '1:128383511539:ios:abc093ed6b1b52dbbbc086',
    messagingSenderId: '128383511539',
    projectId: 'leylaninpaltarlariapp',
    storageBucket: 'leylaninpaltarlariapp.firebasestorage.app',
    iosBundleId: 'com.example.myNewApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCCGlaR71oG1rbZ5Y-a10J_TUt7NC_glk',
    appId: '1:128383511539:ios:abc093ed6b1b52dbbbc086',
    messagingSenderId: '128383511539',
    projectId: 'leylaninpaltarlariapp',
    storageBucket: 'leylaninpaltarlariapp.firebasestorage.app',
    iosBundleId: 'com.example.myNewApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrWDLG-yB1sA29aqg-xAE_yOwYcCyRMIU',
    appId: '1:128383511539:web:803cf392eb0d119bbbc086',
    messagingSenderId: '128383511539',
    projectId: 'leylaninpaltarlariapp',
    authDomain: 'leylaninpaltarlariapp.firebaseapp.com',
    storageBucket: 'leylaninpaltarlariapp.firebasestorage.app',
  );
}
